baseURL = "/"
relativeurls = true
languageCode = "en-us"
title = "Hey, what's here?"
theme = "clement"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params]
    description = "Notes to self about things I pick up for a closer look."
    footer = "&copy; [Gabi Huiber](https:://ghuiber.netlify.com) 2017 | [Github](https://github.com/ghuiber)"
    
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"    
