name = "Clement"
license = "MIT"
licenselink = "https://github.com/ghuiber/clement/blob/master/LICENSE.md"
description = "A minimal theme spun off Yihui Xie's hugo-xmin, with a color scheme inspired by Clement St. in San Francisco."
homepage = "https://ghuiber.netlify.com/"
tags = ["minimal", "starter"]
features = ["blog"]
min_version = "0.31.1"

[author]
  name = "Gabi Huiber"
  homepage = "https://ghuiber.netlify.com"

[original]
  name = "hugo-xmin"
  homepage = "https://xmin.yihui.name"
  repo = "https://github.com/yihui/hugo-xmin"
